name: Build & Deploy to DigitalOcean

on:
  workflow_dispatch: # Déclencher uniquement sur la branche principale
    inputs:
      tag_name:
        description: "Tag to use for the Docker image"
        required: true
        default: "latest"
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          export VITE_KEYCLOAK_URL=https://auth.speech-analytics.fr
          export VITE_KEYCLOAK_REALM=speech-analytics
          export VITE_KEYCLOAK_CLIENT=speech-analytics-front-end
          export VITE_API_URL=https://api.speech-analytics.fr
          docker build -t speech_analytics_web:${{ github.event.inputs.tag_name }} -t speech_analytics_web:latest -f ./deployment/Dockerfile.app .

      - name: Install doctl (DigitalOcean CLI)
        run: |
          sudo snap install doctl

      - name: Authenticate with DigitalOcean
        env:
          DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
        run: |
          doctl auth init -t "$DIGITALOCEAN_ACCESS_TOKEN"

      - name: Login to Registry
        env:
          DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
        run: |
          sudo snap connect doctl:dot-docker
          doctl registry login

      - name: Push Docker Image
        run: |
          docker tag speech_analytics_web:${{ github.event.inputs.tag_name }} registry.digitalocean.com/speech-analytics/speech_analytics_web:${{ github.event.inputs.tag_name }}
          docker tag speech_analytics_web:latest registry.digitalocean.com/speech-analytics/speech_analytics_web:latest
          docker push registry.digitalocean.com/speech-analytics/speech_analytics_web:${{ github.event.inputs.tag_name }}
          docker push registry.digitalocean.com/speech-analytics/speech_analytics_web:latest
